include:
  - project: "ghsc/esi/esi-templates"
    ref: main
    file:
      - ".setup_conda.yml"
      - ".rules.yml"
      - ".default_rules.yml"
      - ".deploy_rules.yml"
      - ".run_tests.yml"
      - ".deploy_to_testpypi_by_tag.yml"
      - ".deploy_to_pypi_by_tag.yml"
  - local: ".deploy_to_testpypi_by_tag_multi_arch.yml"
  - local: ".deploy_to_pypi_by_tag_multi_arch.yml"

default:
  image: code.usgs.gov:5001/devops/images/usgs/python:3.12-build
  tags:
    - build
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]

# repository rules
.fork: &fork
  if: >
    $CI_PROJECT_PATH != 'ghsc/esi/esi-core'
    && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  variables:
    ENVIRONMENT: development

.upstream: &upstream
  if: >
    $CI_PROJECT_PATH == 'ghsc/esi/esi-core'
    && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    ENVIRONMENT: staging

stages:
  - test
  - deploy

run tests:
  rules:
    - *fork
    - *upstream
  script:
    - curl -sSL https://get.docker.com/ | sh
    - apt-get -y install gcc git
    - curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
    - bash miniconda.sh -f -b -p miniconda
    - . miniconda/etc/profile.d/conda.sh
    - conda install pip
    - pip install .
    - pip install pytest
    - pytest .
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  stage: test

  #Deploy to TestPyPi:
  #  rules:
  #    - !reference [.deploy, rules]
  #
  #  before_script:
  #    - curl -sSL https://get.docker.com/ | sh
  #    - apt-get -y install gcc git
  #    - curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
  #    - bash miniconda.sh -f -b -p miniconda
  #    - . miniconda/etc/profile.d/conda.sh
  #    - conda install pip
  #    - pip install -e .[dev,test,build,all]

  #  extends: .deploy-to-testpypi-by-tag-multi-arch
  #  variables:
  #    DOCKER_HOST: tcp://docker:2375/
  #    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    #    DOCKER_TLS_CERTDIR: ""
    #  stage: deploy

Deploy to PyPi:
  #  needs:
  #    - job: Deploy to TestPyPi
  rules:
    - !reference [.deploy, rules]

  before_script:
    - curl -sSL https://get.docker.com/ | sh
    - apt-get -y install gcc git
    - curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
    - bash miniconda.sh -f -b -p miniconda
    - . miniconda/etc/profile.d/conda.sh
    - conda install pip
    - pip install -e .[dev,test,build,all]

  extends: .deploy-to-pypi-by-tag-multi-arch
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  stage: deploy
