default:
  image: ${DEVOPS_REGISTRY}usgs/conda:latest
  tags:
    - development

# repository rules
.fork: &fork
  if: >
    $CI_PROJECT_PATH != 'ghsc/esi/esi-core'
    && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  variables:
    ENVIRONMENT: development

.upstream: &upstream
  if: >
    $CI_PROJECT_PATH == 'ghsc/esi/esi-core'
    && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    ENVIRONMENT: staging

stages:
  - test

run tests:
  rules:
    - *fork
    - *upstream
  script:
    - sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*
    - sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*
    - yum -y install gcc git
    - source /etc/profile.d/conda.sh
    - conda install -c conda-forge python=3.10
    - pip install .
    - pip install pytest
    - pytest .
  stage: test

