include:
  - project: "ghsc/esi/esi-templates"
    ref: main
    file:
      - ".setup_conda.yml"
      - ".rules.yml"
      - ".default_rules.yml"
      - ".deploy_rules.yml"
      - ".run_tests.yml"
  - local: ".deploy_to_testpypi_by_tag_multi_arch.yml"
  - local: ".deploy_to_pypi_by_tag_multi_arch.yml"

default:
  image: code.usgs.gov:5001/devops/images/usgs/python:3.12-build
  tags:
    - build
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]

# repository rules
.fork: &fork
  if: >
    $CI_PROJECT_PATH != 'ghsc/esi/esi-core'
    && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  variables:
    ENVIRONMENT: development

.upstream: &upstream
  if: >
    $CI_PROJECT_PATH == 'ghsc/esi/esi-core'
    && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    ENVIRONMENT: staging

stages:
  - test
  - deploy

run tests:
  rules:
    - *fork
    - *upstream
  script:
    - apt-get -y install gcc git
    - pip install .
    - pip install pytest
    - pytest .
  stage: test

  #Deploy to TestPyPi:
  #  rules:
  #    - !reference [.deploy, rules]
  #
  #  before_script:
  #    - apt-get -y install gcc git

  #  extends: .deploy-to-testpypi-by-tag-multi-arch
    #  stage: deploy

Deploy to PyPi:
  #  needs:
  #    - job: Deploy to TestPyPi
  rules:
    - !reference [.deploy, rules]

  before_script:
    - apt-get -y install gcc git

  extends: .deploy-to-pypi-by-tag-multi-arch
  stage: deploy
